export { Speko } from './lib/client.js';
export { SpekoApiError, SpekoAuthError, SpekoRateLimitError } from './lib/errors.js';
export type {
  SpekoClientOptions,
  KeySource,
  UsageSummary,
  UsageByProvider,
  UsageQueryParams,
  OrganizationBalance,
  CreditLedgerEntry,
  CreditLedgerKind,
  CreditLedgerPage,
  CreditLedgerQueryParams,
  OptimizeFor,
  RoutingIntent,
  PipelineConstraints,
  TranscribeOptions,
  TranscribeResult,
  SynthesizeOptions,
  SynthesizeResult,
  ChatMessage,
  ChatTool,
  ChatToolCall,
  ChatToolChoice,
  ChatToolExecutionMode,
  ChatToolSource,
  CompleteParams,
  CompleteResult,
  RealtimeProvider,
  RealtimeToolSpec,
  RealtimeConnectParams,
  RealtimeFrame,
  RealtimeEventHandler,
  RealtimeSessionHandle,
  VoiceDialParams,
  VoiceDialResult,
  PhoneNumberDirection,
  PhoneNumberRow,
  PhoneNumberCreateParams,
  PhoneNumberUpdateParams,
  AvailablePhoneNumber,
  PhoneNumberSearchParams,
} from './lib/types/index.js';
