export { Speko } from './lib/client.js';
export { SpekoApiError, SpekoAuthError, SpekoRateLimitError } from './lib/errors.js';
export type {
  SpekoClientOptions,
  KeySource,
  UsageSummary,
  UsageByProvider,
  UsageQueryParams,
  OrganizationBalance,
  CreditLedgerEntry,
  CreditLedgerKind,
  CreditLedgerPage,
  CreditLedgerQueryParams,
  Vertical,
  OptimizeFor,
  RoutingIntent,
  PipelineConstraints,
  TranscribeOptions,
  TranscribeResult,
  SynthesizeOptions,
  SynthesizeResult,
  ChatMessage,
  CompleteParams,
  CompleteResult,
} from './lib/types/index.js';
